export const R2_EVENT_TRY_LCP_PASS = "R2_EVENT_TRY_LCP_PASS";
export const R2_EVENT_TRY_LCP_PASS_RES = "R2_EVENT_TRY_LCP_PASS_RES";

export const R2_EVENT_DEVTOOLS = "R2_EVENT_DEVTOOLS";

export const R2_EVENT_READIUMCSS = "R2_EVENT_READIUMCSS";

export const R2_EVENT_LINK = "R2_EVENT_LINK";

export const R2_EVENT_WEBVIEW_READY = "R2_EVENT_WEBVIEW_READY";
